ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
db:
  url: jdbc:sqlite:data/dev.db
  driver: org.sqlite.JDBC
dao:
  mode: in-memory # options: in-memory | sqlite
